apiVersion: v1
kind: ConfigMap
metadata:
  name: naas-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "naas.labels" . | nindent 4 }}
data:
  NATS_SERVERS: {{ include "naas.natsServers" . | quote }}
  NAAS_WORKER_PROCESSES: {{ .Values.worker.processes | quote }}
  {{- range $key, $val := .Values.config }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
